=== heniancheng/FRODO/src/frodo2/algorithms/XCSPschema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- 
FRODO: a FRamework for Open/Distributed Optimization
Copyright (C) 2008-2013  Thomas Leaute, Brammert Ottens & Radoslaw Szymanek

FRODO is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

FRODO is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


How to contact the authors: 
<http://frodo2.sourceforge.net/>
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>XML schema file for FRODO's XCSP format (restricted subset). </xs:documentation>
	</xs:annotation>

	<xs:element name="instance">
		<xs:annotation>
			<xs:documentation>A DisCSP or DCOP problem instance</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element minOccurs="1" maxOccurs="1" ref="presentation"/>
				<xs:element minOccurs="1" maxOccurs="1" ref="agents"/>
				<xs:element minOccurs="1" maxOccurs="1" ref="domains"/>
				<xs:element minOccurs="1" maxOccurs="1" ref="variables"/>
				<xs:element minOccurs="0" maxOccurs="1" ref="relations"/>
				<xs:element minOccurs="0" maxOccurs="1" ref="probabilities"/>
				<xs:element minOccurs="1" maxOccurs="1" ref="constraints"/>
			</xs:all>
		</xs:complexType>

		<xs:key name="domKey">
			<xs:annotation>
				<xs:documentation>Each domain must have a unique name</xs:documentation>
			</xs:annotation>
			<xs:selector xpath="domains/domain"/>
			<xs:field xpath="@name"/>
		</xs:key>
		
		<xs:keyref name="domRef" refer="domKey">
			<xs:annotation>
				<xs:documentation>Each variable must reference an existing domain</xs:documentation>
			</xs:annotation>
			<xs:selector xpath="variables/variable"/>
			<xs:field xpath="@domain"/>
		</xs:keyref>

		<xs:key name="relKey">
			<xs:annotation>
				<xs:documentation>Each relation or probability law must have a unique name</xs:documentation>
			</xs:annotation>
			<xs:selector xpath="relations/relation|probabilities/probability"/>
			<xs:field xpath="@name"/>
		</xs:key>
		
		<xs:keyref name="relRef" refer="relKey">
			<xs:annotation>
				<xs:documentation>Each constraint must reference an existing relation or probability law</xs:documentation>
			</xs:annotation>
			<xs:selector xpath="constraints/constraint"/>
			<xs:field xpath="@reference"/>
		</xs:keyref>
	</xs:element>
	
	<xs:element name="presentation">
		<xs:annotation>
			<xs:documentation>General information about the problem instance</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="stats" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="optional"/>
			<xs:attribute default="XCSP 2.1_FRODO" name="format" type="xs:string" use="optional"/>
			<xs:attribute name="maxConstraintArity" type="xs:positiveInteger" use="optional">
				<xs:annotation>
					<xs:documentation>The maximum number of variables in a constraint scope</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute default="false" name="maximize" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>If true, then this is a maximization problem; if false, then this is a minimization problem</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:anyAttribute processContents="skip" />
		</xs:complexType>
	</xs:element>

	<xs:element name="agents">
		<xs:annotation>
			<xs:documentation>The list of agents</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="agent"/>
			</xs:sequence>
			<xs:attribute name="nbAgents" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="domains">
		<xs:annotation>
			<xs:documentation>The list of variable domains</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="domain"/>
			</xs:sequence>
			<xs:attribute name="nbDomains" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="variableValue">
		<xs:annotation>
			<xs:documentation>Variables are allowed to take decimal values (positive or negative), and are also allowed be infinite (positively or negatively)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="(\+|-)?(infinity|\d+(\.\d*)?)"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="domain">
		<xs:annotation>
			<xs:documentation>A domain is a white-space separated list of either variable values, or intervals in the form min..max, or a mix thereof</xs:documentation>
		</xs:annotation>
		<xs:list>
			<xs:simpleType>
				<xs:union memberTypes="variableValue">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="(\+|-)?(infinity|\d+(\.\d*)?)\.\.(\+|-)?(infinity|\d+(\.\d*)?)"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:union>
			</xs:simpleType>
		</xs:list>
	</xs:simpleType>
	
	<xs:simpleType name="identifier">
		<xs:annotation>
			<xs:documentation>An identifier (i.e. name of a domain, relation,...) may only contain letters, digits and underscores, and may not start with a digit</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z_]([a-zA-Z\d_])*"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="varID">
		<xs:restriction base="xs:ID">
			<xs:pattern value="[a-zA-Z_]([a-zA-Z\d_])*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="agent">
		<xs:annotation>
			<xs:documentation>An agent</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="name" type="varID" use="required"/>
			<xs:anyAttribute processContents="skip" />
		</xs:complexType>
	</xs:element>

	<xs:element name="domain">
		<xs:annotation>
			<xs:documentation>A variable domain</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="domain">
					<xs:attribute name="name" type="identifier" use="required"/>
					<xs:attribute name="nbValues" type="xs:positiveInteger" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="variables">
		<xs:annotation>
			<xs:documentation>The list of variables</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="variable"/>
			</xs:sequence>
			<xs:attribute name="nbVariables" type="xs:nonNegativeInteger" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="variable">
		<xs:annotation>
			<xs:documentation>A variable</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="agent" type="xs:IDREF" use="optional">
				<xs:annotation>
					<xs:documentation>The name of the agent that owns this variable</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="name" type="varID" use="required"/>
			<xs:attribute name="type" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>A variable may be of type "random"</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="domain" type="identifier" use="required"/>
			<xs:anyAttribute processContents="skip" />
		</xs:complexType>
	</xs:element>

	<xs:element name="relations">
		<xs:annotation>
			<xs:documentation>A list of relations that are used to define extensional soft constraints</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="relation"/>
			</xs:sequence>
			<xs:attribute name="nbRelations" type="xs:nonNegativeInteger" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="weightedTuples">
		<xs:annotation>
			<xs:documentation>Weighted tuples must be in a format that looks like the following: 
utility1 : value1forVar1 value1forVar2 | value2forVar1 value2forVar2 | utility2 : value3forVar1 value3forVar2
where variable values and utility values can be integer numbers, decimal numbers, or even infinity or -infinity. 
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:pattern value="(\+|-)?(infinity|\d+(\.\d*)?)\s?:\s?(\+|-)?(infinity|\d+(\.\d*)?)(\s(\+|-)?(infinity|\d+(\.\d*)?))*(\s?\|\s?((\+|-)?(infinity|\d+(\.\d*)?)\s?:\s?)?(\+|-)?(infinity|\d+(\.\d*)?)(\s(\+|-)?(infinity|\d+(\.\d*)?))*)*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="relation">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="weightedTuples">
					<xs:attribute name="name" type="identifier" use="required"/>
					<xs:attribute name="defaultCost" type="xs:string" use="optional">
						<xs:annotation>
							<xs:documentation>The cost (or utility) associated with tuples that are not explicitely listed</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute fixed="soft" name="semantics" type="xs:string" use="required"/>
					<xs:attribute name="nbTuples" type="xs:nonNegativeInteger" use="required">
						<xs:annotation>
							<xs:documentation>Must be equal to the number of tuples explicitely given in the list</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="arity" type="xs:positiveInteger" use="required">
						<xs:annotation>
							<xs:documentation>The number of variables involved</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="probabilities">
		<xs:annotation>
			<xs:documentation>A list of probability laws for random variables</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="probability"/>
			</xs:sequence>
			<xs:attribute name="nbProbabilities" type="xs:nonNegativeInteger" use="required"/>
	</xs:complexType>
	</xs:element>

	<xs:element name="probability">
		<xs:annotation>
			<xs:documentation>A probability law for a single random variable (joint probability laws are currently unsupported)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="weightedTuples">
					<xs:attribute name="name" type="identifier" use="required"/>
					<xs:attribute fixed="soft" name="semantics" type="xs:string" use="required"/>
					<xs:attribute name="defaultProb" type="xs:float" use="optional">
						<xs:annotation>
							<xs:documentation>The probability associated with tuples that are not explicitely listed</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="nbTuples" type="xs:nonNegativeInteger" use="required">
						<xs:annotation>
							<xs:documentation>Must be equal to the number of tuples explicitely given in the list</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute fixed="1" name="arity" type="xs:positiveInteger" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="constraints">
		<xs:annotation>
			<xs:documentation>A list of constraints</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="0" ref="constraint"/>
			</xs:sequence>
			<xs:attribute name="nbConstraints" type="xs:nonNegativeInteger" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="constraint">
		<xs:annotation>
			<xs:documentation>A constraint over one or more variables</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="reference" type="identifier" use="required">
				<xs:annotation>
					<xs:documentation>Must refer to the name of an existing relation or probability law</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="scope" use="required">
				<xs:annotation>
					<xs:documentation>The whitespace-separated list of variables in the constraint's scope</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:list itemType="xs:IDREF"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="arity" type="xs:nonNegativeInteger" use="required">
				<xs:annotation>
					<xs:documentation>The number of variables involved</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="agent" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>The name of the agent that owns this constraint. If set to PUBLIC, the constraint is public. </xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:anyAttribute processContents="skip" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== heniancheng/FRODO/test_problems/graphColoring.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="src/frodo2/algorithms/XCSPschema.xsd">
  <presentation name="graphColoring_1385451189874" maxConstraintArity="2" maximize="false" format="XCSP 2.1_FRODO">
    <stats name="number of nodes">7</stats>
    <stats name="target density">0.4</stats>
    <stats name="true average density">0.38095238095238093</stats>
    <stats name="target unary tightness">0.0</stats>
    <stats name="true average unary tightness">0.0</stats>
    <stats name="number of colors">3</stats>
    <stats name="number of uncontrollable nodes">0</stats>
    <stats name="number of disconnected components">1</stats>
    <stats name="max degree">3</stats>
  </presentation>
  <agents nbAgents="7">
    <agent name="a0" />
    <agent name="a1" />
    <agent name="a2" />
    <agent name="a3" />
    <agent name="a4" />
    <agent name="a5" />
    <agent name="a6" />
  </agents>
  <domains nbDomains="1">
    <domain name="colors" nbValues="3">1..3</domain>
  </domains>
  <variables nbVariables="7">
    <variable name="n0" domain="colors" agent="a0" />
    <variable name="n1" domain="colors" agent="a1" />
    <variable name="n2" domain="colors" agent="a2" />
    <variable name="n3" domain="colors" agent="a3" />
    <variable name="n4" domain="colors" agent="a4" />
    <variable name="n5" domain="colors" agent="a5" />
    <variable name="n6" domain="colors" agent="a6" />
  </variables>
  <relations nbRelations="1">
    <relation name="neq" semantics="soft" arity="2" defaultCost="0" nbTuples="3">infinity: 1 1 | 2 2 | 3 3</relation>
  </relations>
  <constraints nbConstraints="8">
    <constraint name="n0_neq_n3" scope="n0 n3" arity="2" reference="neq" />
    <constraint name="n4_neq_n5" scope="n4 n5" arity="2" reference="neq" />
    <constraint name="n1_neq_n4" scope="n1 n4" arity="2" reference="neq" />
    <constraint name="n3_neq_n6" scope="n3 n6" arity="2" reference="neq" />
    <constraint name="n1_neq_n2" scope="n1 n2" arity="2" reference="neq" />
    <constraint name="n0_neq_n1" scope="n0 n1" arity="2" reference="neq" />
    <constraint name="n2_neq_n3" scope="n2 n3" arity="2" reference="neq" />
    <constraint name="n4_neq_n6" scope="n4 n6" arity="2" reference="neq" />
  </constraints>
</instance>

=== heniancheng/FRODO/test_problems/custom_problem1.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="src/frodo2/algorithms/XCSPschema.xsd">
<presentation name="customized_dcop_problem" maxConstraintArity="2" maximize="false" format="XCSP 2.1_FRODO">
    <stats name="number of nodes">4</stats>
  </presentation>
  <agents nbAgents="4">
    <agent name="a1" />
    <agent name="a2" />
    <agent name="a3" />
    <agent name="a4" />
  </agents>
  <domains nbDomains="1">
    <domain name="domain_values" nbValues="2">0..1</domain>
  </domains>
  <variables nbVariables="4">
    <variable name="n1" domain="domain_values" agent="a1" />
    <variable name="n2" domain="domain_values" agent="a2" />
    <variable name="n3" domain="domain_values" agent="a3" />
    <variable name="n4" domain="domain_values" agent="a4" />
  </variables>
  <relations nbRelations="1">
    <relation name="cost_constraint1_2" semantics="soft" arity="2" defaultCost="0" nbTuples="4">5: 0 0 |  8: 0 1 | 20: 1 0 | 3: 1 1</relation>
	<relation name="cost_constraint1_3" semantics="soft" arity="2" defaultCost="0" nbTuples="4">5: 0 0 | 10: 0 1 | 20: 1 0 | 3: 1 1</relation>
	<relation name="cost_constraint2_3" semantics="soft" arity="2" defaultCost="0" nbTuples="4">5: 0 0 |  4: 0 1 |  3: 1 0 | 3: 1 1</relation>
	<relation name="cost_constraint2_4" semantics="soft" arity="2" defaultCost="0" nbTuples="4">3: 0 0 |  8: 0 1 | 10: 1 0 | 3: 1 1</relation>
  </relations>
  <constraints nbConstraints="8">
    <constraint name="n1_con_n2" scope="n1 n2" arity="2" reference="cost_constraint1_2" />
    <constraint name="n1_con_n3" scope="n1 n3" arity="2" reference="cost_constraint1_3" />
    <constraint name="n2_con_n3" scope="n2 n3" arity="2" reference="cost_constraint2_3" />
    <constraint name="n2_con_n4" scope="n2 n4" arity="2" reference="cost_constraint2_4" />
  </constraints>
</instance>

=== heniancheng/FRODO/src/frodo2/solutionSpaces/JaCoP/tests/Instances/Ext/coloring3.xml
<instance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../algorithms/XCSPschema.xsd">
	<presentation name="sampleProblem" maxConstraintArity="2" maximize="false" format="XCSP 2.1_FRODO" />
	<agents nbAgents="3">
		<agent name="agentX" />
		<agent name="agentY" />
		<agent name="agentZ" />
	</agents>
	<domains nbDomains="1">
		<domain name="three_colors" nbValues="3">1..3</domain>
	</domains>
	<variables nbVariables="3">
		<variable name="X" domain="three_colors" agent="agentX" />
		<variable name="Y" domain="three_colors" agent="agentY" />
		<variable name="Z" domain="three_colors" agent="agentZ" />
	</variables>
	<relations nbRelations="1">
		<relation name="NEQ" arity="2" nbTuples="5" semantics="soft" defaultCost="0">infinity: 1 1|2 2|3 3|1 2|2 1</relation>
	</relations>
	<constraints nbConstraints="3">
		<constraint name="X_and_Y_have_different_colors" arity="2" scope="X Y" reference="NEQ" />
		<constraint name="X_and_Z_have_different_colors" arity="2" scope="X Z" reference="NEQ" />
		<constraint name="Y_and_Z_have_different_colors" arity="2" scope="Y Z" reference="NEQ" />
	</constraints>
</instance>

=== heniancheng/FRODO/src/frodo2/solutionSpaces/JaCoP/tests/Instances/Ext/party_ext.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../algorithms/XCSPschema.xsd">
  <presentation name="partyProblem" maximize="false" format="XCSP 2.1_FRODO" maxConstraintArity="3" />
  <agents nbAgents="4">
  	<agent name="p0" />
  	<agent name="p1" />
  	<agent name="p2" />
  	<agent name="p3" />
  </agents>
  <domains nbDomains="1">
    <domain name="Strategies" nbValues="2">0 1</domain>
  </domains>
  <variables nbVariables="10">
    <variable name="p0s0" domain="Strategies" agent="p0" />
    <variable name="p0s1" domain="Strategies" agent="p0" />
    <variable name="p0s2" domain="Strategies" agent="p0" />
    <variable name="p1s1" domain="Strategies" agent="p1" />
    <variable name="p1s0" domain="Strategies" agent="p1" />
    <variable name="p2s2" domain="Strategies" agent="p2" />
    <variable name="p2s0" domain="Strategies" agent="p2" />
    <variable name="p2s3" domain="Strategies" agent="p2" />
    <variable name="p3s3" domain="Strategies" agent="p3" />
    <variable name="p3s2" domain="Strategies" agent="p3" />
  </variables>
  <relations nbRelations="5">
    <relation name="EQ" arity="2" nbTuples="2" semantics="soft" defaultCost="infinity">0: 0 0 | 1 1</relation>
    <relation name="p0_rel" arity="3" semantics="soft" defaultCost="0" nbTuples="4">infinity: 
0 0 1|
0 1 1|
1 0 1|
1 1 1</relation>
    <relation name="p1_rel" arity="2" semantics="soft" defaultCost="0" nbTuples="2">infinity: 
0 1|
1 0</relation>
    <relation name="p2_rel" arity="3" semantics="soft" defaultCost="0" nbTuples="4">infinity: 
0 0 1|
0 1 1|
1 0 0|
1 1 1</relation>
    <relation name="p3_rel" arity="2" semantics="soft" defaultCost="0" nbTuples="2">infinity: 
0 1|
1 0</relation>
  </relations>
  <constraints nbConstraints="10">
    <constraint name="p0s1_EQ_p1s1" arity="2" scope="p0s1 p1s1" reference="EQ" />
    <constraint name="p0s2_EQ_p2s2" arity="2" scope="p0s2 p2s2" reference="EQ" />
    <constraint name="p0_const" arity="3" scope="p0s1 p0s2 p0s0" reference="p0_rel" />
    <constraint name="p1s0_EQ_p0s0" arity="2" scope="p1s0 p0s0" reference="EQ" />
    <constraint name="p1_const" arity="2" scope="p1s0 p1s1" reference="p1_rel" />
    <constraint name="p2s0_EQ_p0s0" arity="2" scope="p2s0 p0s0" reference="EQ" />
    <constraint name="p2s3_EQ_p3s3" arity="2" scope="p2s3 p3s3" reference="EQ" />
    <constraint name="p2_const" arity="3" scope="p2s0 p2s3 p2s2" reference="p2_rel" />
    <constraint name="p3s2_EQ_p2s2" arity="2" scope="p3s2 p2s2" reference="EQ" />
    <constraint name="p3_const" arity="2" scope="p3s2 p3s3" reference="p3_rel" />
  </constraints>
</instance>

=== heniancheng/FRODO/meetingScheduling_EAV.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="src/frodo2/algorithms/XCSPschema.xsd">
  <presentation name="randomMeetingScheduling_1401430583109" format="XCSP 2.1_FRODO" maximize="false">
    <stats name="formulation">EAV</stats>
    <stats name="number of agents">6</stats>
    <stats name="number of meetings">3</stats>
    <stats name="number of agents per meeting">2</stats>
    <stats name="number of time slots">4</stats>
    <stats name="constraint violation cost">infinity</stats>
    <stats name="target probability of being unavailable at any given time slot">0.0</stats>
    <stats name="average probability of being unavailable at any given time slot">0.0</stats>
    <stats name="maximum random cost of being unavailable at any given time slot">null</stats>
  </presentation>
  <agents nbAgents="4">
    <agent name="a1" />
    <agent name="a3" />
    <agent name="a4" />
    <agent name="a5" />
  </agents>
  <domains nbDomains="1">
    <domain name="slots" nbValues="4">1..4</domain>
  </domains>
  <variables nbVariables="3">
    <variable name="m0" domain="slots" agent="a5" />
    <variable name="m1" domain="slots" agent="a3" />
    <variable name="m2" domain="slots" agent="a4" />
  </variables>
  <relations nbRelations="2">
    <relation name="trivial1" semantics="soft" arity="1" nbTuples="1" defaultCost="0">0:1</relation>
    <relation name="NEQ" semantics="soft" arity="2" nbTuples="4" defaultCost="0">infinity: 1 1|2 2|3 3|4 4</relation>
  </relations>
  <constraints nbConstraints="4">
    <constraint name="m1_neq_m0_a1" arity="2" scope="m1 m0" reference="NEQ" agent="a1" />
    <constraint name="a3_availability" arity="1" scope="m1" reference="trivial1" agent="a3" />
    <constraint name="a4_availability" arity="1" scope="m2" reference="trivial1" agent="a4" />
    <constraint name="m2_neq_m0_a5" arity="2" scope="m2 m0" reference="NEQ" agent="a5" />
  </constraints>
</instance>

=== heniancheng/FRODO/test_problems/custom_problem3.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="src/frodo2/algorithms/XCSPschema.xsd">
<presentation name="customized_dcop_problem" maxConstraintArity="2" maximize="false" format="XCSP 2.1_FRODO">
    <stats name="number of nodes">14</stats>
  </presentation>
  <agents nbAgents="14">
    <agent name="a0" />
    <agent name="a1" />
    <agent name="a2" />
    <agent name="a3" />
	<agent name="a4" />
	<agent name="a5" />
	<agent name="a6" />
	<agent name="a7" />
	<agent name="a8" />
	<agent name="a9" />
	<agent name="a10" />
	<agent name="a11" />
	<agent name="a12" />
	<agent name="a13" />
  </agents>
  <domains nbDomains="1">
    <domain name="domain_values" nbValues="2">0..1</domain>
  </domains>
  <variables nbVariables="14">
    <variable name="x0"  domain="domain_values" agent="a0" />
    <variable name="x1"  domain="domain_values" agent="a1" />
    <variable name="x2"  domain="domain_values" agent="a2" />
    <variable name="x3"  domain="domain_values" agent="a3" />
	<variable name="x4"  domain="domain_values" agent="a4" />
	<variable name="x5"  domain="domain_values" agent="a5" />
	<variable name="x6"  domain="domain_values" agent="a6" />
	<variable name="x7"  domain="domain_values" agent="a7" />
	<variable name="x8"  domain="domain_values" agent="a8" />
	<variable name="x9"  domain="domain_values" agent="a9" />
	<variable name="x10" domain="domain_values" agent="a10" />
	<variable name="x11" domain="domain_values" agent="a11" />
	<variable name="x12" domain="domain_values" agent="a12" />
	<variable name="x13" domain="domain_values" agent="a13" />
  </variables>
  <relations nbRelations="1">
    <relation name="cost_constraint" semantics="soft" arity="2" defaultCost="0" nbTuples="4">1: 0 0 | 3: 0 1 | 2: 1 0 | 4: 1 1</relation>
  </relations>
  <constraints nbConstraints="17">
    <constraint name="x0_con_x1"  scope="x0 x1"  arity="2" reference="cost_constraint" />
    <constraint name="x0_con_x2"  scope="x0 x2"  arity="2" reference="cost_constraint" />
    <constraint name="x0_con_x8"  scope="x0 x8"  arity="2" reference="cost_constraint" />
    <constraint name="x0_con_x11" scope="x0 x11" arity="2" reference="cost_constraint" />
	<constraint name="x1_con_x3"  scope="x1 x3"  arity="2" reference="cost_constraint" />
	<constraint name="x1_con_x4"  scope="x1 x4"  arity="2" reference="cost_constraint" />
	<constraint name="x1_con_x8"  scope="x1 x8"  arity="2" reference="cost_constraint" />
	<constraint name="x2_con_x5"  scope="x2 x5"  arity="2" reference="cost_constraint" />
	<constraint name="x2_con_x6"  scope="x2 x6"  arity="2" reference="cost_constraint" />
	<constraint name="x2_con_x12" scope="x2 x12" arity="2" reference="cost_constraint" />
	<constraint name="x3_con_x7"  scope="x3 x7"  arity="2" reference="cost_constraint" />
	<constraint name="x3_con_x8"  scope="x3 x8"  arity="2" reference="cost_constraint" />
	<constraint name="x4_con_x9"  scope="x4 x9"  arity="2" reference="cost_constraint" />
	<constraint name="x4_con_x10" scope="x4 x10" arity="2" reference="cost_constraint" />
	<constraint name="x5_con_x11" scope="x5 x11" arity="2" reference="cost_constraint" />
	<constraint name="x5_con_x12" scope="x5 x12" arity="2" reference="cost_constraint" />
	<constraint name="x6_con_x13" scope="x6 x13" arity="2" reference="cost_constraint" />
  </constraints>
</instance>
